### ISSUE TITLE
Make level layouts for medieval level 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#11]

**Comment by kennyrkun** [comment]
documents can be stored [here](https://github.com/spacielhop/documents)

**Comment by Froggythedoctor** [comment]
its just a task assignment 
its not actually going to be stored here

**Comment by kennyrkun** [comment]
I know.

When you create the documents, store them [here](https://github.com/spacielhop/documents), so that all of us can view and collaborate if necessary.
