### ISSUE TITLE
Game crashes constantly when running

### ISSUE THREAD

**Issue by kennyrkun** [kennyrkun/quantumjump#16]
The game crashes very often when you try to play it.

Fix it.

@Froggythedoctor fix it.

**Comment by Froggythedoctor** [comment]
ive found the issue
dont know how to fix

**Comment by kennyrkun** [comment]
Can you provide more information detailing the issue?

**Comment by Froggythedoctor** [comment]
its a problem with the actual project being bloated with things

**Comment by Froggythedoctor** [comment]
i don't know how to fix it still 
cleaning up some of the unneeded items seems to have zero effect

**Comment by kennyrkun** [comment]
Have you tried not using Gaia?

**Comment by Froggythedoctor** [comment]
its not gaia however i belive its something to so with me trying to organize.. will look further into it 
👍

**Comment by kennyrkun** [comment]
I have a pretty clustered game project, but not Gaia, and I haven't crashed at all.

**Comment by Froggythedoctor** [comment]
🤔🤔
