### ISSUE TITLE
The Project is 4.45 GB 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#20]
time to figure out why

**Comment by kennyrkun** [comment]
The GitHub repository accounts for nearly 2.15 gigabytes of this total size.

**Comment by kennyrkun** [comment]
The actual size of the project doesn't really matter. I can tell you for a fact that the size of the project being 4 gigabytes is not the reason the game is crashing (how would GTA V even be possible?)

There is a misconfiguration somewhere, or something is going wrong. You need to find out what it is and fix it.

**Comment by Froggythedoctor** [comment]
this may just be a limitation of the unity 
because i've found no logical explanation for this happening

**Comment by kennyrkun** [comment]
My project is nearly 5.4 gigabytes and it's never crashed, or even frozen up on me. It is not Unity's fault, it is yours. Find out what it is, and fix it. Create a completely new project if you have to.

**Comment by Froggythedoctor** [comment]
in conclusion  and through investigation 
it appears unity just hates me
