### ISSUE TITLE
Next level will not be loaded after a level that contains water.

### ISSUE THREAD

**Issue by kennyrkun** [kennyrkun/quantumjump#22]
An error is thrown when the script tries to destroy the water asset. If you're playing a level that has water, Island, for instance, and the game tries to change levels, it will throw an error and the script will not finish executing.

Technically, the problem is just that the player is never teleported to the next level, but that's too difficult to explain. We need to fix the same error anyway, so meh.

**Comment by Froggythedoctor** [comment]
how do we fix it

**Comment by kennyrkun** [comment]
it's a code issue, I will have to investigate further later.

something in Game.cs I think

**Comment by kennyrkun** [comment]
The issue resolved itself.
