### ISSUE TITLE
I need to build a wall(fence)

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#25]
City Objects (modeling)

- [x] Fencing
- [x] Stop sign
- [x] Bus stop 

*Buildings
- [x] Apartment
- [x] Skyscraper

**Comment by ThatOneGirlThere** [comment]
that tells us nothing

**Comment by Froggythedoctor** [comment]
![example](https://user-images.githubusercontent.com/25568249/68697972-86c28a00-0545-11ea-9d31-45e9d3d6de60.PNG)
something like this please 
im needing obsticals for the city

**Comment by Froggythedoctor** [comment]
ill post more exaple as i find them

**Comment by Froggythedoctor** [comment]
![Example 2](https://user-images.githubusercontent.com/25568249/68698270-34ce3400-0546-11ea-9ac2-e97682a536d5.PNG)
![Exmple 3](https://user-images.githubusercontent.com/25568249/68698273-35ff6100-0546-11ea-9db6-0ca4e2dca940.PNG)

**Comment by ThatOneGirlThere** [comment]
okie

**Comment by ThatOneGirlThere** [comment]
@Froggythedoctor @kennyrkun @Ottersolutions Look at the word file in the folder or I'll slay you all
![Capture](https://user-images.githubusercontent.com/56169971/68796500-9a8af080-0618-11ea-9c41-86147ab738f0.PNG)

**Comment by kennyrkun** [comment]
that wasn't necessary >:(

**Comment by ThatOneGirlThere** [comment]
>:-(((((

**Comment by Ottersolutions** [comment]
@ThatOneGirlThere you came all the way over here to ask me for my username just to @ me in a thing telling me to look at a thing

**Comment by ThatOneGirlThere** [comment]
You're username wasn't showing up (╯°□°)╯︵ ┻━┻

**Comment by Froggythedoctor** [comment]
Please keep the messaging in here to a minimum only do it when necessary
