### ISSUE TITLE
The teleport Script and trigger dosnt work on my scene 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#27]
I dont know how to fix it

**Comment by kennyrkun** [comment]
works on my machine.

**Comment by Froggythedoctor** [comment]
butit dosnt work on mine

**Comment by kennyrkun** [comment]
have you tried fixing it?

**Comment by Froggythedoctor** [comment]
i dont know how to

**Comment by kennyrkun** [comment]
Have you tried learning how to?

**Comment by Froggythedoctor** [comment]
![image](https://user-images.githubusercontent.com/25568249/68708071-926b7c00-0558-11ea-9920-56ba820cff78.png)
