### ISSUE TITLE
Ruined Building

### ISSUE THREAD

**Issue by ThatOneGirlThere** [kennyrkun/quantumjump#3]
Modern destroyed building

- [x] Modeled
- [x] Uv'ed

**Comment by kennyrkun** [comment]
Is this part of [Sprint #1](https://github.com/EOCTech/quantumjump/milestone/1)?

**Comment by Froggythedoctor** [comment]
No it is going to be going into sprint 2

**Comment by ThatOneGirlThere** [comment]
we didnt have a sprint 2 yet when I put it up

**Comment by Froggythedoctor** [comment]
hey why do you have 3 buildings 
i only need you to do one

**Comment by Froggythedoctor** [comment]
This needs to be done this week
