### ISSUE TITLE
Need textures on building models 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#5]
please i need it so we don't have a rainbow city 

- [x] Building 1 textures and in Finished folder
- [x] Building 2 Textured and in Finished folder 
- [x] building 3 textured and in Finished folder

**Comment by Ottersolutions** [comment]
give me the fREAKIN TEXTURES YOU ABSOLUTE GOBLIN

**Comment by Ottersolutions** [comment]
ive gotta remake the buildings now so ill have these done in afew days
