### ISSUE TITLE
Texture all models that are done 

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#7]

**Comment by kennyrkun** [comment]
Perhaps you should maintain a list of all models currently waiting on UV.

Maybe create an issue in [spacielhop/assets](https://github.com/spacielhop/assets) for every asset, and give them each unique labels (done, waiting for uv, waiting for textures, etc).

This way, we can keep fine details.

**Comment by kennyrkun** [comment]
Closed because this isn't really helping us.
