### ISSUE TITLE
List of Models needing completion

### ISSUE THREAD

**Issue by Froggythedoctor** [kennyrkun/quantumjump#8]
This list needs to be completed by the end of [Sprint #2](https://github.com/kennyrkun/quantumjump/milestone/2).

@ThatOneGirlThere:
- [x] Dumpster
- [x] Trash cans
- [x] Power lines 
- [x] Crashed Space Ship 

@Ottersolutions:
- [x] Village Housing (2-4 different variants(low priority))
- [x] Village Well
- [x]  Pull cart 
- [x]  Pile of Hay 

You can choose what you do. Leave a comment listing what models you're going to take care of so you guys don't work on the same stuff.

**Comment by Ottersolutions** [comment]
gonna yoink village housing, village well, and pull cart

**Comment by ThatOneGirlThere** [comment]
1. Dumpster
2. Trash cans 
3. Power lines
4. Crashed space ship

**Comment by ThatOneGirlThere** [comment]
If im not done with the building today do you want me to finish it up next sprint?

**Comment by Ottersolutions** [comment]
kachow. all models are done
