### ISSUE TITLE
the models That Boss man gave me

### ISSUE THREAD

**Issue by MMMsooTasty** [kennyrkun/quantumjump#9]
- Shipwrecked pirate boat
   - [x] model
   - [x] UV
   - [x] export
- dung
- [x] broke and deleted itself

- firetruck (for truck month)
   - [x] model
   - [x] UV
   - [ ] export
- street light
   - [ ] model
   - [ ] UV
   - [ ] export
- police car
   - [ ] model
   - [ ] UV
   - [ ] export

**Comment by Froggythedoctor** [comment]
These are being worked on right Jeffery?

**Comment by Ottersolutions** [comment]
done
